apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  type: NodePort
  selector:
    app: reviews-service
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30081
