apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      containers:
        - name: reviews-service
          image: reviews-service:1.0
          imagePullPolicy: Never
          #image: sagariprashanth/favorites-service:1.0
          #imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/reviews_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
